version: 1

sources:
  - name: raw
    database: warehouse
    tables:
      - name: seller
        columns:
          - name: seller_id
            description: ''
          - name: seller_zip_code_prefix
            description: ''
          - name: seller_city
            description: ''
          - name: seller_state
            description: ''
