version: 1

sources:
  - name: raw
    database: warehouse
    tables:
      - name: order
        description: ''
        columns:
          - name: order_id
            description: ''
          - name: customer_id
            description: ''
          - name: order_status
            description: ''
          - name: order_purchase_timestamp
            description: ''
          - name: order_approved_at
            description: ''
          - name: order_delivered_carrier_date
            description: ''
          - name: order_delivered_customer_date
            description: ''
          - name: order_estimated_delivery_date
            description: ''
      - name: product
        description: ''
        columns:
          - name: product_id
            description: ''
          - name: product_category_name
            description: ''
          - name: product_name_lenght
            description: ''
          - name: product_description_lenght
            description: ''
          - name: product_photos_qty
            description: ''
          - name: product_weight_g
            description: ''
          - name: product_length_cm
            description: ''
          - name: product_height_cm
            description: ''
          - name: product_width_cm
            description: ''
      - name: seller
        description: ''
        columns:
          - name: seller_id
            description: ''
          - name: seller_zip_code_prefix
            description: ''
          - name: seller_city
            description: ''
          - name: seller_state
            description: ''
      - name: customer
        description: ''
        columns:
          - name: customer_id
            description: ''
          - name: customer_unique_id
            description: ''
          - name: customer_zip_code_prefix
            description: ''
          - name: customer_city
            description: ''
          - name: customer_state
            description: ''
      - name: order_payment
        description: ''
        columns:
          - name: order_id
            description: ''
          - name: payment_sequential
            description: ''
          - name: payment_type
            description: ''
          - name: payment_installments
            description: ''
          - name: payment_value
            description: ''
      - name: geolocation
        description: ''
        columns:
          - name: geolocation_zip_code_prefix
            description: ''
          - name: geolocation_lat
            description: ''
          - name: geolocation_lng
            description: ''
          - name: geolocation_city
            description: ''
          - name: geolocation_state
            description: ''
      - name: order_review
        description: ''
        columns:
          - name: review_id
            description: ''
          - name: order_id
            description: ''
          - name: review_score
            description: ''
          - name: review_comment_title
            description: ''
          - name: review_comment_message
            description: ''
          - name: review_creation_date
            description: ''
          - name: review_answer_timestamp
            description: ''
      - name: order_item
        description: ''
        columns:
          - name: order_id
            description: ''
          - name: order_item_id
            description: ''
          - name: product_id
            description: ''
          - name: seller_id
            description: ''
          - name: shipping_limit_date
            description: ''
          - name: price
            description: ''
          - name: freight_value
            description: ''